version: '3'

services:
  sx-api:
    build: ./sx-api
    container_name: sx-api
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET: ${SECRET}
      SECRET_REFRESH: ${SECRET_REFRESH}
    ports:
      - "3003:3001"
    depends_on:
      - sx-db
    networks:
      - sx-network

  sx-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5436:5432
    networks:
      - sx-network
    volumes:
      - sx-db-data:/var/lib/postgresql/data

networks:
  sx-network:
    driver: bridge

volumes:
  sx-db-data:
    name: sx-db-data