version: '3'

services:
  sx-desktop:
    build:
      context: ./sx-desktop
      args:
        - VITE_API_URL=${API_URL_COMPOSE}
    container_name: sx-desktop-web
    ports:
      - '9002:9002'
    networks:
      - sx-network
    depends_on:
      - sx-api

  sx-api:
    build: ./sx-api
    container_name: sx-api
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET: ${SECRET}
      SECRET_REFRESH: ${SECRET_REFRESH}
      EMAIL_TRANSPORT: ${EMAIL_TRANSPORT}
    ports:
      - '3003:3003'
    depends_on:
      - sx-db
    networks:
      - sx-network
    volumes:
      - sx-static-data:/app/src/resources/static

  sx-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5436:5432
    networks:
      - sx-network
    volumes:
      - sx-db-data:/var/lib/postgresql/data

networks:
  sx-network:
    driver: bridge

volumes:
  sx-db-data:
    name: sx-db-data
  sx-static-data:
    name: sx-static-data
